services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
      - "33740:33740/udp"
    volumes:
      - ./dist:/var/lib/grafana/plugins/gt7-telemetry
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=gt7-telemetry
    user: "472"

volumes:
  grafana-storage: