export const gt7Options = [
  { label: 'PackageID', value: 'PackageID' },
  { label: 'BestLap', value: 'BestLap' },
  { label: 'LastLap', value: 'LastLap' },
  { label: 'CurrentLap', value: 'CurrentLap' },
  { label: 'CurrentGear', value: 'CurrentGear' },
  { label: 'SuggestedGear', value: 'SuggestedGear' },
  { label: 'FuelCapacity', value: 'FuelCapacity' },
  { label: 'CurrentFuel', value: 'CurrentFuel' },
  { label: 'Boost', value: 'Boost' },
  { label: 'TyreDiameterFL', value: 'TyreDiameterFL' },
  { label: 'TyreDiameterFR', value: 'TyreDiameterFR' },
  { label: 'TyreDiameterRL', value: 'TyreDiameterRL' },
  { label: 'TyreDiameterRR', value: 'TyreDiameterRR' },
  { label: 'TyreSpeedFL', value: 'TyreSpeedFL' },
  { label: 'TyreSpeedFR', value: 'TyreSpeedFR' },
  { label: 'TyreSpeedRL', value: 'TyreSpeedRL' },
  { label: 'TyreSpeedRR', value: 'TyreSpeedRR' },
  { label: 'CarSpeed', value: 'CarSpeed' },
  { label: 'TyreSlipRatioFL', value: 'TyreSlipRatioFL' },
  { label: 'TyreSlipRatioFR', value: 'TyreSlipRatioFR' },
  { label: 'TyreSlipRatioRL', value: 'TyreSlipRatioRL' },
  { label: 'TyreSlipRatioRR', value: 'TyreSlipRatioRR' },
  { label: 'TimeOnTrack', value: 'TimeOnTrack' },
  { label: 'TotalLaps', value: 'TotalLaps' },
  { label: 'CurrentPosition', value: 'CurrentPosition' },
  { label: 'TotalPositions', value: 'TotalPositions' },
  { label: 'CarID', value: 'CarID' },
  { label: 'Throttle', value: 'Throttle' },
  { label: 'RPM', value: 'RPM' },
  { label: 'RPMRevWarning', value: 'RPMRevWarning' },
  { label: 'Brake', value: 'Brake' },
  { label: 'RPMRevLimiter', value: 'RPMRevLimiter' },
  { label: 'EstimatedTopSpeed', value: 'EstimatedTopSpeed' },
  { label: 'Clutch', value: 'Clutch' },
  { label: 'ClutchEngaged', value: 'ClutchEngaged' },
  { label: 'RPMAfterClutch', value: 'RPMAfterClutch' },
  { label: 'OilTemp', value: 'OilTemp' },
  { label: 'WaterTemp', value: 'WaterTemp' },
  { label: 'OilPressure', value: 'OilPressure' },
  { label: 'RideHeight', value: 'RideHeight' },
  { label: 'TyreTempFL', value: 'TyreTempFL' },
  { label: 'TyreTempFR', value: 'TyreTempFR' },
  { label: 'TyreTempRL', value: 'TyreTempRL' },
  { label: 'TyreTempRR', value: 'TyreTempRR' },
  { label: 'SuspensionFL', value: 'SuspensionFL' },
  { label: 'SuspensionFR', value: 'SuspensionFR' },
  { label: 'SuspensionRL', value: 'SuspensionRL' },
  { label: 'SuspensionRR', value: 'SuspensionRR' },
  { label: 'Gear1', value: 'Gear1' },
  { label: 'Gear2', value: 'Gear2' },
  { label: 'Gear3', value: 'Gear3' },
  { label: 'Gear4', value: 'Gear4' },
  { label: 'Gear5', value: 'Gear5' },
  { label: 'Gear6', value: 'Gear6' },
  { label: 'Gear7', value: 'Gear7' },
  { label: 'Gear8', value: 'Gear8' },
  { label: 'PositionX', value: 'PositionX' },
  { label: 'PositionY', value: 'PositionY' },
  { label: 'PositionZ', value: 'PositionZ' },
  { label: 'VelocityX', value: 'VelocityX' },
  { label: 'VelocityY', value: 'VelocityY' },
  { label: 'VelocityZ', value: 'VelocityZ' },
  { label: 'RotationPitch', value: 'RotationPitch' },
  { label: 'RotationYaw', value: 'RotationYaw' },
  { label: 'RotationRoll', value: 'RotationRoll' },
  { label: 'AngularVelocityX', value: 'AngularVelocityX' },
  { label: 'AngularVelocityY', value: 'AngularVelocityY' },
  { label: 'AngularVelocityZ', value: 'AngularVelocityZ' },
  { label: 'Local Velocity X', value: 'LocalVelocityX' },
  { label: 'Local Velocity Y', value: 'LocalVelocityY' },
  { label: 'Local Velocity Z', value: 'LocalVelocityZ' },
  { label: 'Acceleration X', value: 'AccelerationX' },
  { label: 'Acceleration Y', value: 'AccelerationY' },
  { label: 'Acceleration Z', value: 'AccelerationZ' },
  { label: 'G-Force X', value: 'GForceX' },
  { label: 'G-Force Y', value: 'GForceY' },
  { label: 'G-Force Z', value: 'GForceZ' },
  { label: 'Roll', value: 'Roll' },
  { label: 'Pitch', value: 'Pitch' },
  { label: 'Yaw', value: 'Yaw' },
  { label: 'IsPaused', value: 'IsPaused' },
  { label: 'InRace', value: 'InRace' },

  { label: 'All', value: '*' },
];
